<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Sample Test Suite" duration-ms="30" started-at="2016-08-13T19:57:44Z" finished-at="2016-08-13T19:57:44Z">
    <groups>
    </groups>
    <test name="Sample Test" duration-ms="30" started-at="2016-08-13T19:57:44Z" finished-at="2016-08-13T19:57:44Z">
      <class name="test.NewTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:test.NewTest@956de9]" name="beforeTest" is-config="true" duration-ms="13" started-at="2016-08-14T01:27:44Z" finished-at="2016-08-14T01:27:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="testFunc()[pri:0, instance:test.NewTest@956de9]" name="testFunc" duration-ms="3" started-at="2016-08-14T01:27:44Z" finished-at="2016-08-14T01:27:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFunc -->
        <test-method status="FAIL" signature="testFunc1()[pri:1, instance:test.NewTest@956de9]" name="testFunc1" duration-ms="1" started-at="2016-08-14T01:27:44Z" finished-at="2016-08-14T01:27:44Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at test.NewTest.testFunc1(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.TestNG.privateMain(TestNG.java:1385)
	at org.testng.TestNG.main(TestNG.java:1354)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFunc1 -->
      </class> <!-- test.NewTest -->
    </test> <!-- Sample Test -->
  </suite> <!-- Sample Test Suite -->
</testng-results>
